services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSOWRD:-password}
      POSTGRES_DB: ${DB_NAME:-user_management}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_user_management:/var/lib/postgresql/data
  mailpit:
        image: axllent/mailpit
        container_name: user-management-mailpit
        volumes:
            - ./data:/data
        ports:
            - 8025:8025
            - 1025:1025
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
volumes:
  postgres_user_management: