version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_management:/var/lib/postgresql/data

volumes:
  postgres_user_management: