services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSOWRD:-password}
      POSTGRES_DB: ${DB_NAME:-user_management}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_user_management:/var/lib/postgresql/data

volumes:
  postgres_user_management: